version: "3.8"
services:

    sensor1:
        build: .
        environment:
            - SENSOR_NAME=sensor1

    sensor2:
        depends_on:
            - sensor1
        build: .
        environment:
            - SENSOR_NAME=sensor2


    sensor3:
        depends_on:
            - sensor2
        build: .
        environment:
            - SENSOR_NAME=sensor3


    sensor4:
        depends_on:
            - sensor3
        build: .
        environment:
            - SENSOR_NAME=sensor4


    sensor5:
        depends_on:
            - sensor4
        build: .
        environment:
            - SENSOR_NAME=sensor5


    sensor6:
        depends_on:
            - sensor5
        build: .
        environment:
            - SENSOR_NAME=sensor6
